### ISSUE TITLE
Android 运行报错

### ISSUE THREAD

**Issue by shesl-meow** [ZZMarquis/gmhelper#33]
```
W/System.err: java.security.NoSuchAlgorithmException: No provider found for SM4/ECB/NoPadding
        at javax.crypto.Cipher.createCipher(Cipher.java:529)
        at javax.crypto.Cipher.getInstance(Cipher.java:413)
        at org.zz.gmhelper.SM4Util.generateEcbCipher(SM4Util.java:175)
        at org.zz.gmhelper.SM4Util.encrypt_Ecb_NoPadding(SM4Util.java:66)
```

**Comment by ZZMarquis** [comment]
你翻一下以前的issue，有人提过Android上遇到的问题，可能跟你是一样的

**Comment by ZZMarquis** [comment]
#18
