### ISSUE TITLE
sm2生成私钥时，报错ECPrivateKeyParameters.<init>(Unknown Source)

### ISSUE THREAD

**Issue by sg4567** [ZZMarquis/gmhelper#42]
`String priHex = "ff3794cc7a83920e0f6d406817d97a3b876631ee4ddfafe87622e92966738c33";`
`ECPrivateKeyParameters priKey = new ECPrivateKeyParameters(new BigInteger(ByteUtils.fromHexString(priHex)), M2Util.DOMAIN_PARAMS);`

当私钥为f开头时，都会报错如下：
Exception in thread "main" java.lang.IllegalArgumentException: Scalar is not in the interval [1, n - 1]
	at org.bouncycastle.crypto.params.ECDomainParameters.validatePrivateScalar(Unknown Source)
	at org.bouncycastle.crypto.params.ECPrivateKeyParameters.<init>(Unknown Source)

但是前补个0就可正常使用，请解惑啊，谢谢。

**Comment by ZZMarquis** [comment]
f开头说明第一个比特位是1，也就是表示这个数是负数，但是ECC算法里要求私钥是正数，所以需要补0来表示这个数是正数。
或者可以写成这样：
`ECPrivateKeyParameters priKey = new ECPrivateKeyParameters(new BigInteger(1, ByteUtils.fromHexString(priHex)), M2Util.DOMAIN_PARAMS);`
明确指定大叔的符号位为正。

**Comment by sg4567** [comment]
确实是这个问题，太效率啦！！！
